add solutions for 9-module tasks
js-tasks-ru/nodejs-20210618_vera-lobacheva9 pull request #5
Opened 2021-08-03 13:36 UTC by vera-l

2021-08-03 13:37 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-03 14:12 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-08-03 14:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2021-08-04 12:15 UTC, tadjik1 commented on 09-email/01-registration/controllers/registration.js
> +  if (existingUser) {
в принципе да, так тоже можно сделать, но помните про принцип атомарности? отсутствие пользователя не гарантировано во время следующего вызова, потому что эти вызовы асинхронные, т.е. кто-то может "успеть" создать пользователя.
безопаснее как обычно просто создавать пользователя, и обрабатывать возможные потенциальные ошибки БД.

2021-08-04 12:16 UTC, tadjik1 requested changes
отличные решения! 
небольшой (но принципиальный) нюанс касается обработки ошибки создания пользователя, который уже есть, его нужно поправить

2021-08-04 13:35 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-08-04 18:24 UTC, tadjik1 approved these changes
Отлично 👍

2021-08-04 18:25 UTC, merged